[DEFAULT]
ignoreip = 127.0.0.1/8 ::1
banaction = iptables-allports[chain=DOCKER-USER]
findtime = 10m
bantime = 1h
maxretry = 10
backend = auto

[album-backend-401]
enabled = true
filter = album-backend-401
logpath = /var/lib/docker/containers/*/*-json.log
findtime = 10m
maxretry = 20
bantime = 30m

[album-auth-bf]
enabled = true
filter = album-backend-auth-bruteforce
logpath = /var/lib/docker/containers/*/*-json.log
findtime = 10m
maxretry = 8
bantime = 24h

[album-backend-scanners]
enabled = true
filter = album-backend-scanners
logpath = /var/lib/docker/containers/*/*-json.log
findtime = 10m
maxretry = 3
bantime = 7d
