[Definition]
failregex = ^.*"log":".* (?:::ffff:)?<HOST> [A-Z]+ /(?:wp-admin|wp-login\\.php|xmlrpc\\.php|\\.env|\\.git|phpmyadmin|cgi-bin|vendor/phpunit|server-status|\\.DS_Store|HNAP1|boaform).*".*$
ignoreregex =
